# ==========================
# == Jekyll Configuration ==
# ==========================
markdown: kramdown
permalink: :title

# ==========================
# == Custom Configuration ==
# ==========================

title: Blog | Hot Dogs and Eggs
subtitle: "The blog of Chris Gallo."
url: http://blog.hotdogsandeggs.com
description: "Blog of Chris Gallo | Sharing what I learn because it pays to be curious."
twitter_username: cjgallo
navigation:
 - title: Blog
   url: /
 - title: People
   url: http://people.hotdogsandeggs.com/
