# Dependencies
markdown: redcarpet
pygments: true

# Setup
title: Hot dogs and eggs blog
url: http://blog.hotdogsandeggs.com
paginate: 10
name: Hot dogs and eggs blog
description: This a story about learning by Chris Gallo

# Permalinks
permalink:        pretty
