# ==========================
# == Jekyll Configuration ==
# ==========================
markdown: kramdown
permalink: :title

# ==========================
# == Custom Configuration ==
# ==========================

title: Blog | Hot Dogs and Eggs
subtitle: "The blog of Chris Gallo."
url: http://hotdogsandeggs.com/
description: "Sharing what I learn because it pays to be curious."
navigation:
 - title: Blog
   url: /
 - title: People
   url: http://people.hotdogsandeggs.com/
 - title: Say hi
   url: https://twitter.com/cjgallo
