# ==========================
# == Jekyll Configuration ==
# ==========================
markdown: rdiscount
permalink: :title

# ==========================
# == Custom Configuration ==
# ==========================

title: Blog | Hot Dogs and Eggs
subtitle: "The blog of Chris Gallo."
url: http://hotdogsandeggs.com/
description: "Sharing what I learn because it pays to be curious."
navigation:
 - title: About
   url: /about/
 - title: Blog
   url: /
 - title: Say hi
   url: /about/#contact