baseURL = "https://blog.hotdogsandeggs.com/"
languageCode = "en-us"
title = "Chris Gallo | Blog"
[permalinks]
    posts = ":slug"

[taxonomies]
  tag = "tags"

[params]

    author = "Chris Gallo"
    description = "You’re reading Hot dogs and eggs, a blog by Chris Gallo since 2014."
    twitter_username = "cjgallo"
